using System;
using System.Runtime.InteropServices;
using System.Threading;

namespace WhisperWin.Core
{
    /// <summary>
    /// Installs a WH_KEYBOARD_LL low-level keyboard hook for a single configurable virtual key
    /// (default: VK_RCONTROL) and drives a <see cref="HotkeyStateMachine"/> from it.
    ///
    /// While recording is active, the hotkey's KEY-DOWN is swallowed (the hook callback returns 1)
    /// so the focused application never sees Right Ctrl go down and cannot fire its own Ctrl-based
    /// shortcuts. The KEY-UP is always allowed to pass through to the OS: hold-promotion happens
    /// asynchronously (via the 30ms poll timer in <see cref="Start"/>, not synchronously on
    /// key-down), so by the time a key-up arrives the OS may already have seen the key-down even
    /// though the state machine is now active. Swallowing that key-up would leave the OS thinking
    /// Right Ctrl is still held, "stuck" until the user taps Ctrl again. A lone Ctrl key-up with no
    /// preceding recognized chord does not trigger any OS/app shortcut, so always letting it through
    /// is safe and keeps every key-down/key-up pair balanced from the OS's point of view.
    ///
    /// C# pitfalls handled here (see design spec):
    ///  - The <see cref="_hookProc"/> delegate is stored in a field so the GC cannot collect it
    ///    while the hook is installed (a classic "hook mysteriously stops firing" bug).
    ///  - The hook callback (<see cref="HookCallback"/>) does no I/O and only touches the state
    ///    machine + raises .NET events; heavy work happens on whatever thread subscribers marshal
    ///    to (e.g. the dispatcher), never inline in the hook.
    ///  - Injected key events (e.g. our own <c>TextInjector</c> synthesizing Ctrl+V via SendInput)
    ///    are ignored so they never feed back into the state machine.
    /// </summary>
    public sealed class HotkeyManager : IDisposable
    {
        private const int WH_KEYBOARD_LL = 13;
        private const int WM_KEYDOWN = 0x0100;
        private const int WM_KEYUP = 0x0101;
        private const int WM_SYSKEYDOWN = 0x0104;
        private const int WM_SYSKEYUP = 0x0105;

        // LLKHF_INJECTED: bit 0x10 of KBDLLHOOKSTRUCT.flags — set for events generated by
        // SendInput (ours or another process's), as opposed to real hardware key events.
        private const int LLKHF_INJECTED = 0x10;

        public const int VK_RCONTROL = 0xA3;

        private readonly int _targetVirtualKey;
        private readonly HotkeyStateMachine _stateMachine;
        private readonly IClock _clock;

        // Keep a strong reference to the delegate for the lifetime of the hook — otherwise the
        // GC can collect it and the hook stops firing (or crashes) unpredictably.
        private readonly LowLevelKeyboardProc _hookProc;
        private IntPtr _hookHandle = IntPtr.Zero;
        private Timer? _holdPollTimer;
        private bool _disposed;

        public HotkeyManager(IClock? clock = null, int targetVirtualKey = VK_RCONTROL)
        {
            _clock = clock ?? new SystemClock();
            _targetVirtualKey = targetVirtualKey;
            _stateMachine = new HotkeyStateMachine(_clock);
            _hookProc = HookCallback; // pin the delegate

            _stateMachine.Started += (s, e) => Started?.Invoke(this, EventArgs.Empty);
            _stateMachine.Stopped += (s, e) => Stopped?.Invoke(this, EventArgs.Empty);
            _stateMachine.Toggled += (s, isOn) => Toggled?.Invoke(this, isOn);
        }

        /// <summary>Fires when recording should start (hold threshold reached).</summary>
        public event EventHandler? Started;

        /// <summary>Fires when recording should stop (hold key released).</summary>
        public event EventHandler? Stopped;

        /// <summary>Fires on double-tap toggle transitions (true = turned on, false = turned off).</summary>
        public event EventHandler<bool>? Toggled;

        public bool IsActive => _stateMachine.IsActive;

        public void Start()
        {
            if (_hookHandle != IntPtr.Zero)
            {
                return;
            }

            using var curProcess = System.Diagnostics.Process.GetCurrentProcess();
            using var curModule = curProcess.MainModule!;
            _hookHandle = SetWindowsHookEx(
                WH_KEYBOARD_LL,
                _hookProc,
                GetModuleHandle(curModule.ModuleName!),
                0);

            if (_hookHandle == IntPtr.Zero)
            {
                var error = Marshal.GetLastWin32Error();
                throw new InvalidOperationException($"Failed to install keyboard hook (Win32 error {error}).");
            }

            // Poll for hold-promotion every 30ms so a sustained press is detected even without
            // relying on OS key-repeat WM_KEYDOWN messages (which some setups suppress).
            _holdPollTimer = new Timer(_ => _stateMachine.CheckHoldPromotion(), null, 30, 30);
        }

        public void Stop()
        {
            _holdPollTimer?.Dispose();
            _holdPollTimer = null;

            if (_hookHandle != IntPtr.Zero)
            {
                UnhookWindowsHookEx(_hookHandle);
                _hookHandle = IntPtr.Zero;
            }

            _stateMachine.Reset();
        }

        private IntPtr HookCallback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            // An exception escaping a low-level hook callback makes Windows silently remove the
            // hook — the hotkey would die until app restart. Swallow everything and pass through.
            try
            {
                if (nCode >= 0)
                {
                    var msg = wParam.ToInt32();
                    var data = Marshal.PtrToStructure<KBDLLHOOKSTRUCT>(lParam);

                    // Ignore synthetic events from SendInput (e.g. our own TextInjector Ctrl+V) so
                    // they never feed back into the state machine.
                    var isInjected = (data.flags & LLKHF_INJECTED) != 0;

                    if (!isInjected && data.vkCode == _targetVirtualKey)
                    {
                        if (msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN)
                        {
                            _stateMachine.OnKeyDown();
                            if (_stateMachine.IsActive)
                            {
                                return (IntPtr)1; // swallow so the focused app never sees Right Ctrl
                            }
                        }
                        else if (msg == WM_KEYUP || msg == WM_SYSKEYUP)
                        {
                            // Always let key-up pass through to the OS — see class remarks. Hold
                            // promotion happens asynchronously, so the OS may have already seen the
                            // key-down even though IsActive is now true; swallowing the matching
                            // key-up here would leave Ctrl "stuck" down until the user tapped it again.
                            _stateMachine.OnKeyUp();
                        }
                    }
                }
            }
            catch
            {
                // Deliberately ignored: better to miss one hotkey event than to lose the hook.
            }

            return CallNextHookEx(_hookHandle, nCode, wParam, lParam);
        }

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }
            _disposed = true;
            Stop();
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct KBDLLHOOKSTRUCT
        {
            public int vkCode;
            public int scanCode;
            public int flags;
            public int time;
            public IntPtr dwExtraInfo;
        }

        private delegate IntPtr LowLevelKeyboardProc(int nCode, IntPtr wParam, IntPtr lParam);

        [DllImport("user32.dll", SetLastError = true)]
        private static extern IntPtr SetWindowsHookEx(int idHook, LowLevelKeyboardProc lpfn, IntPtr hMod, uint dwThreadId);

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool UnhookWindowsHookEx(IntPtr hhk);

        [DllImport("user32.dll")]
        private static extern IntPtr CallNextHookEx(IntPtr hhk, int nCode, IntPtr wParam, IntPtr lParam);

        [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern IntPtr GetModuleHandle(string lpModuleName);
    }
}
